name: Run Swift Package test

on:
  push:

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          swift test
